---
distFolder: ./
setup:
  - name: Setup composer
    action: php-actions/composer@v6
  - name: Setup Node.js v14.x
    action: actions/setup-node@v1
    properties:
      node-version: 14.x
  - name: Make envfile
    action: fmunirdev/envvar-to-dotenv-action@v0.2.0
    environment:
      APP_NAME: Laravel
      APP_ENV: local
      APP_KEY: dummy
      APP_DEBUG: true
      APP_URL: ${{ steps.project.outputs.site-url }}
      LOG_CHANNEL: stack
      LOG_LEVEL: debug
      DB_CONNECTION: sqlite
      BROADCAST_DRIVER: log
      CACHE_DRIVER: file
      FILESYSTEM_DRIVER: local
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: file
      SESSION_LIFETIME: 120
      MAIL_MAILER: smtp
      MAIL_HOST: ${{ secrets.MAIL_HOST }}
      MAIL_PORT: ${{ secrets.MAIL_PORT }}
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      MAIL_ENCRYPTION: ${{ secrets.MAIL_ENCRYPTION }}
      MAIL_FROM_ADDRESS: ${{ secrets.MAIL_FROM_ADDRESS }}
      MAIL_FROM_NAME: "${APP_NAME}"
    properties:
      variableNames: APP_NAME,APP_ENV,APP_KEY,APP_DEBUG,APP_URL,LOG_CHANNEL,LOG_LEVEL,DB_CONNECTION,BROADCAST_DRIVER,CACHE_DRIVER,FILESYSTEM_DRIVER,QUEUE_CONNECTION,SESSION_DRIVER,SESSION_LIFETIME,MAIL_MAILER,MAIL_HOST,MAIL_PORT,MAIL_USERNAME,MAIL_PASSWORD,MAIL_ENCRYPTION,MAIL_FROM_ADDRESS,MAIL_FROM_NAME
      target: .env
build:
  name: Do stuff to deploy to ionos
  command:
    chmod -R 777 storage/framework;
    chmod -R 777 storage/logs;
    php artisan key:generate --force;
    npm ci;
    npm run prod;
    php artisan migrate --force;
